# Generated by Django 4.1.5 on 2023-04-22 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MusicReg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('genre', models.CharField(max_length=100)),
                ('audio', models.FileField(upload_to='song')),
                ('image', models.ImageField(upload_to='songimage')),
                ('duration', models.DurationField()),
                ('album', models.CharField(max_length=100)),
            ],
        ),
    ]
